project:
  type: website
  output-dir: docs

website:
  title: "Daisy Killingley"
  navbar:
    left:
      - href: cv.qmd
        text: CV
      - about.qmd

format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true



